-- MySQL Script generated by MySQL Workbench
-- dom 20 mar 2022 21:31:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rh
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rh` ;

-- -----------------------------------------------------
-- Schema rh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rh` DEFAULT CHARACTER SET utf8 ;
USE `rh` ;

-- -----------------------------------------------------
-- Table `rh`.`acao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`acao` ;

CREATE TABLE IF NOT EXISTS `rh`.`acao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcao` INT NOT NULL,
  `controller` VARCHAR(30) NOT NULL,
  `action` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcao_acao_idx` (`funcao` ASC) VISIBLE,
  CONSTRAINT `fk_funcao_acao`
    FOREIGN KEY (`funcao`)
    REFERENCES `rh`.`funcao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`atestado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`atestado` ;

CREATE TABLE IF NOT EXISTS `rh`.`atestado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario` INT NOT NULL,
  `emissao` DATE NOT NULL,
  `afastamento` DATE NOT NULL,
  `retorno` DATE NOT NULL,
  `quantidade_dias` INT NOT NULL,
  `medico` INT NOT NULL,
  `cid` CHAR(3) NOT NULL,
  `motivo` VARCHAR(160) NOT NULL,
  `observacao` TEXT NULL,
  `inss` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atestado_funcionario_idx` (`funcionario` ASC) VISIBLE,
  INDEX `fk_atestado_medico_idx` (`medico` ASC) VISIBLE,
  CONSTRAINT `fk_atestado_funcionario`
    FOREIGN KEY (`funcionario`)
    REFERENCES `rh`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atestado_medico`
    FOREIGN KEY (`medico`)
    REFERENCES `rh`.`medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`auditoria` ;

CREATE TABLE IF NOT EXISTS `rh`.`auditoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NULL,
  `data` DATETIME NOT NULL,
  `ocorrencia` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `dado_adicional` VARCHAR(8192) NULL,
  `ip` VARCHAR(15) NOT NULL,
  `agent` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auditoria_usuario_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `rh`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`cid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`cid` ;

CREATE TABLE IF NOT EXISTS `rh`.`cid` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(3) NOT NULL,
  `detalhamento` INT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `subitem` TINYINT(1) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`empresa` ;

CREATE TABLE IF NOT EXISTS `rh`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`firewall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`firewall` ;

CREATE TABLE IF NOT EXISTS `rh`.`firewall` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(15) NOT NULL,
  `data` DATETIME NOT NULL,
  `motivo` VARCHAR(160) NOT NULL,
  `lista_branca` TINYINT(1) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`funcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`funcao` ;

CREATE TABLE IF NOT EXISTS `rh`.`funcao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `chave` VARCHAR(45) NOT NULL,
  `grupo` INT NOT NULL,
  `ordem` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupo_funcao_idx` (`grupo` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_funcao`
    FOREIGN KEY (`grupo`)
    REFERENCES `rh`.`grupo_funcao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`funcao_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`funcao_grupo` ;

CREATE TABLE IF NOT EXISTS `rh`.`funcao_grupo` (
  `grupo_id` INT NOT NULL,
  `funcao_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`, `funcao_id`),
  INDEX `fk_grupo_has_funcao_funcao1_idx` (`funcao_id` ASC) VISIBLE,
  INDEX `fk_grupo_has_funcao_grupo1_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_has_funcao_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `rh`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_has_funcao_funcao1`
    FOREIGN KEY (`funcao_id`)
    REFERENCES `rh`.`funcao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `rh`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `cargo` VARCHAR(50) NULL,
  `area` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `cpf` CHAR(11) NOT NULL,
  `pis` CHAR(11) NULL,
  `tipo` INT NOT NULL,
  `data_admissao` DATE NOT NULL,
  `empresa` INT NOT NULL,
  `observacao` TEXT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `probatorio` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_tipo_idx` (`tipo` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `pis_UNIQUE` (`pis` ASC) VISIBLE,
  INDEX `fk_funcionario_empresa_idx` (`empresa` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `rh`.`tipo_funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_empresa`
    FOREIGN KEY (`empresa`)
    REFERENCES `rh`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`grupo` ;

CREATE TABLE IF NOT EXISTS `rh`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `administrativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`grupo_funcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`grupo_funcao` ;

CREATE TABLE IF NOT EXISTS `rh`.`grupo_funcao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `ordem` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`medico` ;

CREATE TABLE IF NOT EXISTS `rh`.`medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `crm` INT NULL,
  `especialidade` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`tipo_funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`tipo_funcionario` ;

CREATE TABLE IF NOT EXISTS `rh`.`tipo_funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rh`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rh`.`usuario` ;

CREATE TABLE IF NOT EXISTS `rh`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(70) NOT NULL,
  `grupo` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `suspenso` TINYINT(1) NOT NULL,
  `verificar` TINYINT(1) NOT NULL,
  `prefid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_grupo_idx` (`grupo` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `prefid_UNIQUE` (`prefid` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_grupo`
    FOREIGN KEY (`grupo`)
    REFERENCES `rh`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
